# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: MavenAuthenticate@0
  inputs:
    artifactsFeeds: 'Maven'
- task: Maven@3
  inputs:
    mavenPomFile: 'basic/pom.xml'
    mavenOptions: '-Xmx3072m'
    options: '-Dupload.url=$(c8y.url) -Dupload.username=$(c8y.user) -Dupload.password=$(c8y.password)'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: CmdLine@2
  inputs:
    script: 'ls -al /home/vsts/work/1/s/basic/target/'